---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: debian9
    box: debian/contrib-stretch64
  - name: debian10
    box: debian/contrib-buster64
  - name: centos7
    box: centos/7
  - name: centos8
    box: centos/8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../..
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
